name: fintech_dark

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.11.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.3

  # Networking
  dio: ^5.5.0+1

  # Local persistence
  shared_preferences: ^2.2.3

  # Functional programming
  dartz: ^0.10.1

  # Charts
  fl_chart: ^0.68.0

  # Formatting
  intl: ^0.19.0

  # Navigation
  go_router: ^16.0.0

  # SVG support
  flutter_svg: ^2.0.10+1

  #DI
  injectable: ^3.0.0

  #Assets
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  carousel_slider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  build_runner: ^2.10.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  injectable_generator: ^3.0.2


flutter:

  uses-material-design: true


  assets:

    # SVG
    - assets/svg/icons/
    - assets/svg/logos/

    # Images
    - assets/images/avatars/
    - assets/images/backgrounds/
    - assets/images/onboarding/
    - assets/images/chip/

    # Animations
    - assets/animations/lottie/
    - assets/animations/rive/

    # Branding
    - assets/branding/


fonts:
  - family: Arimo
    fonts:
      # Regular 400
      - asset: assets/fonts/Arimo/Arimo-Regular.ttf
        weight: 400

      # Regular Italic 400
      - asset: assets/fonts/Arimo/Arimo-Italic.ttf
        weight: 400
        style: italic

      # Medium 500
      - asset: assets/fonts/Arimo/Arimo-Medium.ttf
        weight: 500

      # Medium Italic 500
      - asset: assets/fonts/Arimo/Arimo-MediumItalic.ttf
        weight: 500
        style: italic

      # SemiBold 600
      - asset: assets/fonts/Arimo/Arimo-SemiBold.ttf
        weight: 600

      # SemiBold Italic 600
      - asset: assets/fonts/Arimo/Arimo-SemiBoldItalic.ttf
        weight: 600
        style: italic

      # Bold 700
      - asset: assets/fonts/Arimo/Arimo-Bold.ttf
        weight: 700

      # Bold Italic 700
      - asset: assets/fonts/Arimo/Arimo-BoldItalic.ttf
        weight: 700
        style: italic